CREATE TABLE document_inf (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(50) NOT NULL,
    FILENAME VARCHAR(300) NOT NULL,
    REMARK VARCHAR(300) NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_ID INT(11) DEFAULT NULL,
    PRIMARY KEY (ID),
    KEY FK_DOCUMENT_USER (USER_ID),
    CONSTRAINT FK_DOCUMENT_USER FOREIGN KEY (USER_ID)
        REFERENCES user_inf (ID)
)  ENGINE=INNODB AUTO_INCREMENT=7 DEFAULT CHARSET=UTF8;